# Dockerfile-test-monitor-ubuntu
FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

# Install SNMP daemon + tools
RUN apt-get update && \
    apt-get install -y snmp snmpd iputils-ping net-tools curl vim && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Backup default SNMP configuration
RUN mv /etc/snmp/snmpd.conf /etc/snmp/snmpd.conf.orig

# Copy custom SNMP configuration
COPY snmpd.conf /etc/snmp/snmpd.conf

# Expose SNMP UDP port
EXPOSE 161/udp

# Start SNMP in background and keep container alive
CMD sh -c "killall snmpd 2>/dev/null; snmpd -Lf /dev/null & tail -f /dev/null"

